name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  clojure:
    name: clojure test runner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java for Maven auth
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          server-id: 'cognitect-dev-tools'
          server-username: DEV_TOOLS_USER
          server-password: DEV_TOOLS_PASSWORD

      - name: Install Clojure CLI
        uses: DeLaGuardo/setup-clojure@11.0
        with:
          cli: 1.11.1.1273

      - name: Cache deps
        uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
          key: cljdeps-${{ hashFiles('deps.edn') }}
          restore-keys: cljdeps-

      - name: Dependencies scan
        uses: clj-holmes/clj-watson-action@main
        with:
          aliases: test
          deps-edn-path: 'deps.edn'
          suggest-fix: 'true'
      
      - name: Run tests
        run: clojure -M:test
        env:
          DEV_TOOLS_USER: ${{ secrets.DEV_TOOLS_USER }}
          DEV_TOOLS_PASSWORD: ${{ secrets.DEV_TOOLS_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
